import { Wallet } from './entities/wallet.entity';
import { Repository } from 'typeorm';
import { User } from 'src/users/entities/user.entity';
import { CreatePaystackDto } from './dto/create-paystack.dto';
import { TransactionsService } from 'src/transactions/transactions.service';
import { UsersService } from 'src/users/users.service';
import { SquadPaymentDto } from './dto/payment.squad.dto';
import { CreateTransferDto } from './dto/transfer.sqaud.dto';
import { TransferFundsDto } from './dto/transfer.funds.dto';
export declare class WalletService {
    private walletRepo;
    private txService;
    private usersService;
    private readonly secretKey;
    private readonly baseUrl;
    private readonly SQUAD_SECRET;
    private readonly SQUAD_BASEURL;
    private readonly SQUAD_CALLBACK_URL;
    private readonly SQUAD_MERCHANT_ID;
    constructor(walletRepo: Repository<Wallet>, txService: TransactionsService, usersService: UsersService);
    createWallet(userId: string, currency: string | undefined, user: User): Promise<Wallet>;
    getWalletById(id: string): Promise<Wallet | null>;
    getWalletByUserId(userId: string): Promise<Wallet | null>;
    chargeUserWallet(user: User, amountToCharge: number): Promise<Wallet>;
    updateWalletByUserId(userid: string, criteria: any): Promise<import("typeorm").UpdateResult>;
    updateBalanceByUserId(userid: string, criteria: any): Promise<import("typeorm").UpdateResult>;
    add_to_User_Balance_By_UserId(user: User, amount: number, purpose: string): Promise<Wallet>;
    subtract_from_User_Balance_By_UserId(user: User, amount: number, purpose: string): Promise<Wallet>;
    updateBalanceById(id: string, amount: number): Promise<Wallet>;
    deleteWallet(id: string): Promise<import("typeorm").DeleteResult>;
    get_System_Balance(): Promise<number>;
    paystack_initiate_Payment(userId: string, body: CreatePaystackDto): Promise<import("../shared/interfaces/aResponse").aResponse<any> | undefined>;
    paystack_initialize_transaction(data: CreatePaystackDto): Promise<any>;
    paystack_withdraw(userId: string, amount: number): Promise<import("../shared/interfaces/aResponse").aResponse<boolean> | undefined>;
    private getMaxWithdrawable;
    create_transfer_Request(account_name: string, account_number: string, bank_code: string): Promise<any>;
    initiate_transfer_transaction(recipientCode: string, amount: number): Promise<any>;
    paystack_getBanks(): Promise<import("../shared/interfaces/aResponse").aResponse<any> | undefined>;
    paystack_account_name_look_up(accountNumber: string, bank_code: string): Promise<import("../shared/interfaces/aResponse").aResponse<any> | undefined>;
    private paystack_get_balance;
    private get_total_system_Balance;
    add_to_User_Balance_By_UserId_webhook(user: User, amount: number, purpose: string): Promise<Wallet>;
    squad_initiate_payment(userId: string, body: SquadPaymentDto): Promise<import("../shared/interfaces/aResponse").aResponse<any>>;
    private Squad_initialize_transaction;
    squad_get_Banks(): Promise<import("../shared/interfaces/aResponse").aResponse<any>>;
    squad_withdrawal_engine(dto: CreateTransferDto): Promise<any>;
    squad_withdraw(userId: string, amount: number): Promise<import("../shared/interfaces/aResponse").aResponse<boolean> | undefined>;
    private check_if_funding_date;
    resetAllBalancesToZero(): Promise<void>;
    transfer_from_wallet(sender_userid: string, dto: TransferFundsDto): Promise<import("../shared/interfaces/aResponse").aResponse<number> | undefined>;
    private withdrawable_amount_by_super_admin;
    private transfer_from_one_wallet_to_the_other;
    look_up_for_user_wallet(userid: string): Promise<import("../shared/interfaces/aResponse").aResponse<Wallet> | undefined>;
    initialize_payment_(body: CreatePaystackDto, userId: string): Promise<import("../shared/interfaces/aResponse").aResponse<import("../shared/interfaces/aResponse").aResponse<any> | undefined> | undefined>;
}
