import { ProductCategory } from '../enum/product.category';
import { ProductType } from '../enum/product.types';
import { Review } from './product.review.entity';
import { Gender } from '../enum/gender';
import { User } from 'src/users/entities/user.entity';
import { Song } from 'src/artist_song/entities/songs.entity';
import { ProductColor } from '../enum/product.color';
import { Collection } from 'src/collection/entities/collection.entity';
import { MusicCategory } from 'src/collection/enum/muscic.category';
export declare class Product {
    id: string;
    category: ProductCategory;
    brand: string;
    brandId: string;
    name: string;
    slug: string;
    description: string;
    sku: string;
    price: number;
    compareAtPrice: number;
    stock: number;
    imageUrl: string;
    advertVideoUrl: string;
    colors: ProductColor[];
    images: string[];
    sizes: string[];
    gender: Gender;
    type: ProductType;
    isActive: boolean;
    isFeatured: boolean;
    createdAt: Date;
    updatedAt: Date;
    tagName: string;
    tagSlug: string;
    hasQrCode: boolean;
    createdBy: User;
    reviews: Review[];
    songs: Song[];
    collection: Collection;
    collectionId: string;
    musicCategory: MusicCategory;
}
