export declare enum EmailType {
    CONFIRM_EMAIL = "CONFIRM_EMAIL",
    RESET_PASSWORD = "RESET_PASSWORD",
    TWO_FACTOR_ENABLED = "TWO_FACTOR_ENABLED",
    TWO_FACTOR_LOGIN = "TWO_FACTOR_LOGIN",
    CONTACT_EMAIL_SUBMISSION = "CONTACT_EMAIL_SUBMISSION",
    NEW_INVESTMENT_EMAIL = "NEW_INVESTMENT_EMAIL",
    NEW_SUBSCRIPTION_EMAIL = "NEW_SUBSCRIPTION_EMAIL",
    RENEWED_SUBSCRIPTION = "NEW_SUBSCRIPTION_EMAIL",
    NEW_REVIEW = "NEW_REVIEW",
    REVIEW_ACCEPTED = "REVIEW_ACCEPTED",
    REVIEW_REJECTED = "REVIEW_REJECTED"
}
